import React, { useState } from "react";
import { ChevronDown, ChevronUp, HelpCircle } from "lucide-react";
import { useLanguage } from "./LanguageContext";

interface FAQItem {
  question: string;
  answer: string;
  category: string;
}

export default function FAQ() {
  const { t, language } = useLanguage();
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const getFaqs = (): FAQItem[] => {
    if (language === "hi") {
      return [
        {
          category: "मूल्य निर्धारण और भुगतान",
          question: "क्या शुरुआती कोटेशन मूल्य के अलावा कोई छिपी हुई लागत या अतिरिक्त शुल्क है?",
          answer: "बिल्कुल नहीं। हम पारदर्शी मूल्य निर्धारण में विश्वास करते हैं। हमारे कॉस्ट एस्टीमेटर द्वारा दिखाई गई कुल राशि ही आपकी फाइनल दर होती है। अतिरिक्त शुल्क केवल तभी लागू होते हैं जब आप कॉन्ट्रैक्ट साइन होने के बाद किसी अतिरिक्त पेज या अन्य जटिल सुविधाओं की मांग करते हैं।",
        },
        {
          category: "तैनाती और होस्टिंग",
          question: "क्या आप डोमेन रजिस्ट्रेशन या होस्टिंग सेटअप में सहायता करते हैं?",
          answer: "हाँ, बिल्कुल! हम आपकी वेबसाइट लाइव करने के लिए पूरी सहायता प्रदान करते हैं। चाहे आपकी पसंद Vercel, Netlify, Github Pages, Hostinger हो या AWS, हम डोमेन लिंक करने से लेकर फ्री SSL सुरक्षा प्रमाणपत्र सेटअप करने तक सब कुछ स्वयं संभालते हैं।",
        },
        {
          category: "बौद्धिक संपदा",
          question: "क्या मुझे कस्टम सोर्स कोड का पूरा और स्थायी स्वामित्व मिलता है?",
          answer: "हाँ, 100%। फाइनल भुगतान के बाद, काम के सोर्स कोड का पूरा स्वामित्व आपको ट्रांसफर हो जाता है। कोई छुपा हुआ लाइसेंसिंग शुल्क नहीं है, और आप कोड को अपनी आवश्यकतानुसार कहीं भी रख या बदल सकते हैं।",
        },
        {
          category: "परियोजना की शुरुआत",
          question: "काम शुरू होने का क्या सामान्य तरीका है?",
          answer: "यह सब हमारे संपर्क फ़ॉर्म के माध्यम से शुरू होता है। हमारी टीम 4 घंटे के भीतर आपकी आवश्यकताओं की समीक्षा करती है, 24 घंटे के भीतर एक ड्राफ्ट तैयार करती है, और निश्चित समयसीमा साझा करती है।",
        },
        {
          category: "रखरखाव और सपोर्ट",
          question: "वेबसाइट लॉन्च होने के बाद क्या रखरखाव वारंटी शामिल है?",
          answer: "शुभ डेवलपमेंट्स द्वारा बनाई गई प्रत्येक वेबसाइट में 30 दिनों की मानार्थ तकनीकी वारंटी शामिल है। यदि कोई त्रुटि सामने आती है, या साधारण स्टाइल अपडेट की आवश्यकता होती है, तो हम बिना किसी अतिरिक्त लागत के तुरंत उसका समाधान करते हैं।",
        },
      ];
    }

    return [
      {
        category: "PRICING & PAYMENTS",
        question: "Are there any hidden costs beyond the initial quoted price?",
        answer: "None at all. We believe in strict, upfront quoting. The total generated by our dynamic Cost Estimator acts as the actual statement line for our development. Additional charges only occur if you explicitly request extra custom pages, post-production features, or integrations state after the project contract is signed.",
      },
      {
        category: "DEPLOYMENT & HOSTING",
        question: "Do you assist with domain registration, Google Cloud, or custom hosting setups?",
        answer: "Yes, absolutely! We provide complete technical assistance to deploy your website live. Whether you prefer Vercel, Netlify, Github Pages, Hostinger, AWS, or Cloud Run, we will handle the setup, point your domain names, and configure free global SSL security certificates for your peace of mind.",
      },
      {
        category: "INTELLECTUAL PROPERTY",
        question: "Do I get full ownership of the custom source code?",
        answer: "Yes, 100%. Once the final settlement is registered, client gets the complete, compressed production-ready source code alongside corresponding Git repositories. There are no licensing fees, and you maintain complete autonomy to modify, rename, export, or host the assets anywhere.",
      },
      {
        category: "ONBOARDING TIMELINES",
        question: "What is your typical project onboarding workflow?",
        answer: "It starts when you submit our online Contact Brief (with your customized cost estimate attached). Our engineering leads review specifications within 4 hours, establish a mutual workspace, draft the interactive layout mockup review draft within 24 hours, and configure development timelines to launch.",
      },
      {
        category: "MAINTENANCE & DEPLOYMENT",
        question: "What post-launch support or maintenance warranty is included?",
        answer: "Every website built by Shubh Developments includes a complimentary 30-day technical warranty. If errors surface, layouts react poorly on new devices, or minor typography/style updates are needed, we handle them instantly at absolutely zero extra charges.",
      },
    ];
  };

  const faqs = getFaqs();

  return (
    <section id="faq" className="bg-[#0A0A0A] py-20 relative border-b border-white/10 font-sans">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto space-y-4 mb-20 font-sans">
          <span className="text-[10px] uppercase tracking-[0.3em] text-zinc-500 font-black font-mono block">
            {t("FAQ_TAG")}
          </span>
          <h2 className="text-4xl sm:text-5xl font-black text-white tracking-tighter uppercase leading-[0.95] font-display">
            {t("FAQ_HEADING")}
          </h2>
          <p className="text-zinc-400 text-sm sm:text-base leading-relaxed">
            {t("FAQ_DESC")}
          </p>
        </div>

        {/* FAQ Accordion List - Swiss Modern Layout */}
        <div className="max-w-3xl mx-auto space-y-4 font-sans">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;

            return (
              <div
                key={idx}
                className="bg-[#111111] border border-white/10 transition-colors duration-200"
              >
                {/* Trigger Header */}
                <button
                  onClick={() => setOpenIndex(isOpen ? null : idx)}
                  className="w-full flex items-center justify-between p-6 text-left focus:outline-none cursor-pointer select-none"
                >
                  <div className="space-y-1.5 flex-1 pr-4">
                    <span className="block text-[8px] uppercase tracking-widest font-mono text-zinc-500 font-black">
                      {faq.category}
                    </span>
                    <h3 className="text-sm sm:text-base font-black text-white uppercase tracking-tight font-display">
                      {faq.question}
                    </h3>
                  </div>

                  <div className="h-8 w-8 rounded-none bg-zinc-900 border border-white/10 flex items-center justify-center text-white shrink-0">
                    {isOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                  </div>
                </button>

                {/* Animated Dropdown Panel */}
                {isOpen && (
                  <div className="px-6 pb-6 pt-1 border-t border-white/5">
                    <p className="text-zinc-400 text-xs sm:text-sm leading-relaxed select-text">
                      {faq.answer}
                    </p>
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
